services:
  app:
    build: .
    restart: always
    develop:
      watch:
        - action: rebuild
          path: .
    ports:
      - "4000:4000"
    environment:
      - VAULT_TOKEN=${VAULT_TOKEN}
    depends_on:
      - db
      - s3
      - vault

  db:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  s3:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    restart: always
    environment:
      - MINIO_ROOT_USER=akionka
      - MINIO_ROOT_PASSWORD=password
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - s3data:/data

  vault:
    image: hashicorp/vault:1.19
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_LOCAL_CONFIG: '{"storage": {"file": {"path": "/vault/file"}}, "listener": [{"tcp": { "address": "0.0.0.0:8200", "tls_disable": true}}], "default_lease_ttl": "168h", "max_lease_ttl": "720h", "ui": true}'
    volumes:
      - vaultdata:/vault/file
    command: server
    restart: unless-stopped
    cap_add:
      - IPC_LOCK

volumes:
  pgdata:
  s3data:
  vaultdata:
