services:
  app:
    build: .
    restart: always
    develop:
      watch:
        - action: rebuild
          path: .
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/mydb?sslmode=disable
      - BOT_TOKEN=925294587:AAFS1QWrK7VNBdbjlUrEgS1GPRX8SBD6HN0
    depends_on:
      - db
      - s3

  db:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  s3:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    restart: always
    environment:
      - MINIO_ROOT_USER=akionka
      - MINIO_ROOT_PASSWORD=password
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - s3data:/data

volumes:
  pgdata:
  s3data:
